#!/usr/bin/env python
import re
import sys

arguments = sys.argv
print arguments

FileName = sys.argv[ 1 ]


File = open( FileName, 'r')

Linenumber = 0
OutFileName = 'extracted-test_' + FileName.rsplit( ".", 1 )[ 0 ]  + ".txt"
OutFile = open(OutFileName, 'w')



for Line in File:

	Line = Line.strip()

	if Linenumber > 0:
		#print ( Linenumber )
		#print ( Line )
		#if Linenumber == 3:break

		ElementList = Line.split( '\t' )
		#print( ElementList )
		print( 'Track:{} x:{} y:{} z:{}'.format( ElementList[2], ElementList[8], ElementList[9], ElementList[10] ) )
		#print (ext)
		#OutFile.write ('\t'.join(ext) + '\n')

	Linenumber = Linenumber + 1	

File.close()
OutFile.close()