#!/usr/bin/env python
import re
import sys
from collections import defaultdict

arguments = sys.argv
print arguments

FileName = sys.argv[ 1 ]


File = open( FileName, 'r')

Linenumber = 0

DictTEx=defaultdict(list)
for Line in File:

	Line = Line.strip()

	if Linenumber > 0:

		ElementList = Line.split( '\t' )
		
		DictTEx[ElementList[3]].append([ ElementList[5], ElementList[6], ElementList[7]])
	
	Linenumber = Linenumber + 1


for keys in DictTEx.keys():
	file=open('track' + keys + '.txt', 'w')
	for output in DictTEx[keys]:
		file.write('Track:{} x:{} y:{} z:{} \n'.format(keys, output[0], output[1], output[2] ) )

File.close()