#!/usr/bin/env python

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import sys
import re

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

FileName = sys.argv[ 1 ]
InFilename = open( FileName, 'r')
#InFilename = open('track12.txt')

SearchString = '^.+x:([\d\.]+) y:([\d\.]+) z:([\d\.]+)'
x,y,z =[],[],[]
for trackxyz in InFilename:

	Result = re.search( SearchString, trackxyz )
	x.append(float(Result.group(1)))
	y.append(float(Result.group(2)))
	z.append(float(Result.group(3)))
	#print (x,y,z)

ax.scatter(x, y, z, c='r', marker='o')

ax.set_xlabel('x axis')
ax.set_xlabel('y axis')
ax.set_xlabel('z axis')
plt.show()