#!/usr/bin/env python
import re
import sys

arguments = sys.argv
print arguments

FileName = sys.argv[ 1 ]



#Linenumber = 0

def extract( Line ):
	SearchString = '^\d+\t[(+*)]\w.*[(+*)]\t(\d+)\t\d+\t\d+\t\d+\.\d+\t\d+\.\d+\t(\d+\.\d+)\t(\d+\.\d+)\t(\d+\.\d+).+'
	Result = re.search( SearchString, Line )

	Trackname = (Result.group(1))
	x = (Result.group(2))
	y = (Result.group(3))
	z = (Result.group(4))
	return [Trackname, x, y, z] 

File = open( FileName, 'r')

Linenumber = 0
OutFileName = 'extracted-test_' + FileName.rsplit( ".", 1 )[ 0 ]  + ".txt"
OutFile = open(OutFileName, 'w')


for Line in File:

	Line = Line.strip()

	if Linenumber > 0:
		#print ( Linenumber )
		#print ( Line )
		#if Linenumber == 3:break

		ext = extract (Line)
		#print (ext)
		OutFile.write ('\t'.join(ext) + '\n')

	Linenumber = Linenumber + 1	

File.close()
OutFile.close()